export const ARTICLE = {
  GET_RECENT_ARTICLES_REQUEST: 'GET_RECENT_ARTICLES_REQUEST',
  GET_RECENT_ARTICLES_SUCCESS: 'GET_RECENT_ARTICLES_SUCCESS',
  GET_RECENT_ARTICLES_ERROR: 'GET_RECENT_ARTICLES_ERROR',

  CREATE_ARTICLE_REQUEST: 'CREATE_ARTICLE_REQUEST',
  CREATE_ARTICLE_SUCCESS: 'CREATE_ARTICLE_SUCCESS',
  CREATE_ARTICLE_ERROR: 'CREATE_ARTICLE_ERROR',
}
