export const ARTICLE = {
  CREATE_ARTICLE: 'CREATE_ARTICLE',
  CREATE_ARTICLE_REQUEST: 'CREATE_ARTICLE_REQUEST',
  CREATE_ARTICLE_SUCCESS: 'CREATE_ARTICLE_SUCCESS',
  CREATE_ARTICLE_ERROR: 'CREATE_ARTICLE_ERROR',
}
